image: node:12

test:
  script:
    - npm install
    - npm install -g sakuradite
    - skd test

publish:
  stage: deploy
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm install
    - npm install -g sakuradite
    - skd build
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG'
