export { KitsuneClient } from './client';
export { deepHashEdge, edgeMap, hashEdge, hashList, hashString, pseudoRandom } from './hash';

export const BIND_COMMAND = 'OQSNYHFqQaJ7hOXEkdmsyBhCiKHkSrcYrRKotJQ8d2I=';
export const BUILT_IN_NODES = 'tM/g7jdtJbdcGwlxr7JRkqQFZvrgxjuj4re4W7aPOtA=';
export const CODE = 'azYkwxJ3FZH7GuMq0z34AAgKDBBFEopUH/qfpdY5l8U=';
export const COMMAND = '2thvxzmTasKTgQrlZkN4Yq4/dCTkemSadDKshbBHi/Q=';
export const ERASE = 'GdMeesaxawq0J2uBEHdytTXNJxbcA0y9kKcyDjVjUh0=';
export const EDGE = '9NeOSRxG9JCQMxyjn8ne/oTHxiaQRfWp4mf96DRzpa0=';
export const GET = 'VrJ1NfyNBVvnZetBWZ1wXcEDotZsSUtl4PRkuNezFVU=';
export const HEAD = 'rVkGcT3cbljIYjNVAwd7NDYzrgsELAQyju9PwhaDVPI=';
export const LINE_TO_STDOUT = 'UXU9B8uJ99bmzmSBfkLDgJJdAIn3G9nVzrJSybVZ1nQ=';
export const LIST = 'B0uC9VnQvcC9I7TubvULT/BV9T3gZqa/xn5HBBfZ0r0=';
export const LIST_N = '4QSz4n2p6jkmOdV73q+qJi6KFyErNflcEAZe3+J4dIs=';
export const MAP_N = '4fXleUmgAKEInL1j7LBttHmXPys4rNJLtrx6jFBW8cg=';
export const MAP_V = 'Pj49hhtbwrg14s2nHt9QoDsquvWBm2zFoDVGKfZ4f7g=';
export const NATIVE_NAME = '5XtkSqo5nMpeo1Mq4ytpeH9JbgtjBihz0LcbciZv4Ug=';
export const PIPE = 'BGbYmq/iTV8cUZ7WvhoeFlTgmYyGZAlPn7amkHgy4Rk=';
export const RANDOM = 'ijJv0As7V8Vk8kx1kL5Rm+LSDyHnfFPazUVtB/pmZiw=';
export const READ = 'Tk6Aj8UWvn+0+nxpAcAuRgWqRRQEB92+8eFp6z3h6CQ=';
export const SET = 'haxZgMavaTh5lUmqXk3dD+A7BViAFQKWXOv7KanC83k=';
export const STRING = 'T5ncjTd6X9U0yxKzgDqpcW4otVk6vVGZL/vfU2TlWI4=';
export const SUPPORTS_COMMAND = 'jY9q3mtCo4e1OJG0MlPGSP4CbGeaT22slihqoXVdDEQ=';
export const TAIL = '6+Ksu9TM316USCs7pm59QsmXygArxBZs0sT/JGovr5Q=';
export const VARIABLE_GET = 'WCFIOmPitmoeRYk+2F6tnqs06kGm+m6e9CHY6rbzNz8=';
export const VARIABLE_SET = 'j07UYfE6s282tTL3rpBGAQhOSBB9jMXjVvKAlkcE9Xc=';
export const WRITE = 'OopQyyACUbZJrQc+uRI50cq25wOY6H50F0m54im0dHE=';
